### PR TITLE
fix No such file or directory error

### PR DESCRIPTION
**Pull request by batnasan**

### CODE REVIEW

**Review by mars — COMMENTED** [review]
If the JS bundle file glob specified does not exist, then why use this buildpack?

I would prefer that the file not found error remain in place, but perhaps the error should reflect that “without the bundle this buildpack is pointless.”

**Comment by batnasan** [comment]
If you use `ls *.js` to loop through JS file, it will fail when the name of the file has space. For example, in my case, I got the js file generated "List - Generatel.2a825668.chunk.js" and the loop returned 3 items 

- List
- \-
- Generatel.2a825668.chunk.js
In fact, we do not need to use `ls` to loop through js files.

**Review by mars — COMMENTED** [review]
This is designed to be overrideable/customizable by setting the config var `JS_RUNTIME_TARGET_BUNDLE` to the path for your app.

See the [parent buildpack’s docs for setting the bundle location](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-custom-bundle-location).

I won’t be accepting this pull request, which would break this buildpack for its main users (through create-react-app-buildpack).

**Comment by batnasan** [comment]
@mars  I was doing some experiment for my personal project, totally forgot about the pull request. 
Apologise for that.

**Pull request closed without merging**
